### ISSUE TITLE
OpticalLaserDelay combines delays for SQS incorrectly

### ISSUE THREAD

**Issue by bj-s** [European-XFEL/EXtra#187]
I found from experimental data, that the `OpticalLaserDelay.total_delay()` function combines the different delay stages for SQS incorrectly. We can compare data from two runs where one or the other available delay stage was moved. (r183: `SQS_ILH_LAS/MOTOR/DELAY_AX_800` / r182: `LA3_LAS_PPL/CTRL/TRGDLY`)

Using the delay computed by the `total_delay` function, a delay dependent step function flips depending on the stage used:

![image](https://github.com/European-XFEL/EXtra/assets/17090727/0429f964-e486-4904-a37d-f09f37f70bc2)

Consequently also the delay of one of the stages is combined with the BAM incorrectly.

**Comment by philsmt** [comment]
Fixed by https://github.com/European-XFEL/EXtra/pull/227
